config/routes.rb
Rails.application.routes.draw do
  resources :jobs, only: [:index, :new, :create, :destroy, :update] do
      collection do
        get 'myjobs'
      end
  end
  get "/jobs/:id", to: "jobs#claim"
  patch "/jobs/:id", to: "jobs#update"

  root 'home#index'
  devise_for :users, :controllers => { registrations: 'users/registrations' } 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
    geocoded_by:pickup_address, latitude: :pickup_latitude, longitude: :pickup_longitude
    after_validation :geocode

    # geocoded_by:drop_off_address, latitude: :drop_off_latitude, longitude: :drop_off_longitude 

    def pickup_address 
        [pickup_street, pickup_city, pickup_postcode, pickup_state].compact.join(", ")
    end
    
    # def drop_off_address
    #     [drop_off_street, drop_off_city, drop_off_postcode, drop_off_state].compact.join(", ")
    # end
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :name, presence: true
  has_many :jobs, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update ]
  
  before_action :authenticate_user!, except:[:index, :show]

  # GET /jobs or /jobs.json
  def index
    # @jobs = Job.near([current_user.latitude, current_user.longitude], 50, :order => :distance)
    @jobs = Job.all
  end

  def myjobs
    # @jobs = Job.all
    @myjobs = current_user.jobs
  end


  # GET /jobs/1 or /jobs/1.json
  def claim
    @job = Job.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end


  # POST /jobs or /jobs.json
  def create
    results = Geocoder.search([job_params[:drop_off_street], job_params[:drop_off_city], job_params[:drop_off_postcode], job_params[:drop_off_state]].compact.join(", "))
    if results.first
      @job = current_user.jobs.new(job_params.merge(:status => 1, :drop_off_latitude => results.first.coordinates[0], :drop_off_longitude=> results.first.coordinates[1] ))
    else
      @job = current_user.jobs.new(job_params.merge(:status => 1))
    end
    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.status == 2
        if @job.update(job_params.merge(:status => 3, :gogeter_id => current_user.id))
          format.html { redirect_to "/jobs", notice: "Job was successfully Completed." }
          format.json { render :job, status: :ok, location: @job }
        else
          format.html { render :claim, status: :unprocessable_entity }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end 
      if @job.update(job_params.merge(:status => 2, :gogeter_id => current_user.id))
        format.html { redirect_to job_url(@job), notice: "Job was successfully Claimed." }
        format.json { render :claim, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:pickup_street, :pickup_city, :pickup_state, :pickup_postcode, :drop_off_street, :drop_off_city, :drop_off_state, :drop_off_postcode, :pickup_latitude, :pickup_longitude, :drop_off_latitude, :drop_off_longitude, :user_id, :gogeter_id, :status)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Go Get", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Jobs", jobs_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Jobs", myjobs_jobs_path, class: "nav-link active" %>
        </li>
      </ul>
    <% if current_user %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
    <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
    <% end %>
    </div>
  </div>
</nav>
<br >

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/jobs/_form.html.erb
<br>
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="col">
    <%= form.label :pickup_street, style: "display: block", class:"form-label" %>
    <%= form.text_field :pickup_street, class: "form-control"%>
    <%= form.label :pickup_city, style: "display: block", class:"form-label" %>
    <%= form.text_field :pickup_city, class: "form-control"%>
    <%= form.label :pickup_postcode, style: "display: block", class:"form-label" %>
    <%= form.text_field :pickup_postcode, class: "form-control"%>
    <%= form.label :pickup_state, style: "display: block", class:"form-label" %>
    <%= form.text_field :pickup_state, class: "form-control"%>
  </div>
  <div class="col">
    <%= form.label :drop_off_street, style: "display: block", class:"form-label" %>
    <%= form.text_field :drop_off_street, class: "form-control"%>
    <%= form.label :drop_off_city, style: "display: block", class:"form-label" %>
    <%= form.text_field :drop_off_city, class: "form-control"%>
    <%= form.label :drop_off_postcode, style: "display: block", class:"form-label" %>
    <%= form.text_field :drop_off_postcode, class: "form-control"%>
    <%= form.label :drop_off_state, style: "display: block", class:"form-label" %>
    <%= form.text_field :drop_off_state, class: "form-control"%>
  </div>
</div>
<br>
  <%= form.submit class: "btn btn-primary"%>
<% end %>

app/views/jobs/_job.html.erb
<tr>
  <td>Awad</td>
  <td><%=[job.pickup_street, job.pickup_city, job.pickup_postcode, job.pickup_city].compact.join(", ") %></td>
  <td><%=[job.drop_off_street, job.drop_off_city, job.drop_off_postcode, job.drop_off_city].compact.join(", ") %></td>
  <td><%= link_to "Show this job", job , class: "btn btn-primary", role: "button" %></td>
</tr>

app/views/jobs/claim.html.erb
<br>
<div class="card" style="width: 50rem;">
  <div class="card-body">
    <h1 class="display-4"> Job Provider : <%= @job.user.name %></h1>
    <p class="lead"> Pickup Address : 
      <%= [@job.pickup_street, @job.pickup_city, @job.pickup_postcode, @job.pickup_city].compact.join(", ") %> 
    </p>
    <p class="lead"> Drop Off Address : 
      <%=[@job.drop_off_street, @job.drop_off_city, @job.drop_off_postcode, @job.drop_off_city].compact.join(", ") %>
    </p>
    <br/>
    
        <%= form_with(model: @job) do |form| %>
    <div class="row">
        <%= form.label :gogeter_id, "Your GoGeter ID", class:"col-sm-4 col-form-label" %>
        <div class="col-sm-8">
            <%= form.number_field :gogeter_id, class: "form-control-plaintext", value: current_user.id %>
        </div>
        </div>
        <br>
    <% if @job.user.id != current_user.id && @job.status == 1%>
        <%= form.submit "Claim", class: "btn btn-primary"%>
    <%  elsif @job.user.id != current_user.id && @job.status == 2 %>
        <%= form.submit "Mark as Complete", class: "btn btn-primary"%>
    <% end %>
    <%= link_to 'Back', jobs_path, class:"btn btn-dark" %>
    <% end %>

  </div>
</div>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Poster</th>
      <th scope="col">Pickup Address</th>
      <th scope="col">Drop off Address</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
<div id="jobs" >
  <% @jobs.each do |job| %>
      <tr>
        <td><%= job.user.name %></td>
        <td><%=[job.pickup_street, job.pickup_city, job.pickup_postcode, job.pickup_city].compact.join(", ") %></td>
        <td><%=[job.drop_off_street, job.drop_off_city, job.drop_off_postcode, job.drop_off_city].compact.join(", ") %></td>
        <%if job.status == 1%>
          <td><span class="badge bg-primary">Available</span></td>
        <%elsif job.status == 2%>
          <td><span class="badge bg-warning text-dark">In Progress</span></td>
        <%else%>
          <td><span class="badge bg-success">Completed</span></td>
        <%end%>
        <td>
          <%= link_to content_tag(:li, fa_icon('show', class: 'fa-solid fa-eye')), job , role: "button" %>      
        </td>
      </tr>

  <% end %>
  </tbody>
</table>
</div>

app/views/jobs/myjobs.html.erb
<h1>My Jobs</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Poster</th>
      <th scope="col">Pickup Address</th>
      <th scope="col">Drop off Address</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
<div id="jobs" >
  <% @myjobs.each do |job| %>
    <tr>
      <td>Awad</td>
      <td><%=[job.pickup_street, job.pickup_city, job.pickup_postcode, job.pickup_city].compact.join(", ") %></td>
      <td><%=[job.drop_off_street, job.drop_off_city, job.drop_off_postcode, job.drop_off_city].compact.join(", ") %></td>
      <td>
        <%= link_to content_tag(:li, fa_icon('show', class: 'fa-solid fa-eye')), job , role: "button" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
  <%= link_to "New job", new_job_path , class: "btn btn-primary", role: "button"  %>
</div>

app/views/jobs/new.html.erb
<br>
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to 'Back', jobs_path, class:"btn btn-dark" %>
</div>

app/views/layouts/_alarts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Go Get</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>
    <%= render "home/header"%>
    <div class ="container">
    <% if notice%>
      <%= render "layouts/alarts"%>
    <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>